const WORDS = [
  {
    word: "alone",
    pos: "adj.",
    definition: "by oneself; not with other people",
    definitionJa: "ひとりで；他の人といない",
    image: "images/alone.png",
    p2sentence: "She was sitting ________ in her room, thinking about her friends.",
    p2sentenceJa: "彼女は友達のことを考えながら、自分の部屋でひとりで座っていた。",
    p3hint: "She felt a________ for the rest of the afternoon.",
    p3hintJa: "彼女はその午後、ずっとひとりだと感じていた。",
    p3blank: "My friend went home early, so I had no one to talk to.",
    p3blankJa: "友達が早く帰ってしまい、話す相手がいなかった。",
    p4definition: "by oneself; not with other people",
    p4definitionJa: "ひとりで；他の人といない",
    usageNote: "「alone」は感情を伴わない中立的な語で、「leave me alone（ひとりにして）」のように使う。寂しさを強調する場合は lonely を使う点に注意。",
    related: ["lonely（寂しい・孤独な、感情が伴う形容詞）", "by myself（自分だけで、口語的な言い方）", "solitary（ひとりを好む・孤独な、文語的）"]
  },
  {
    word: "annoyed",
    pos: "adj.",
    definition: "unhappy; a little angry",
    definitionJa: "不機嫌な；少し腹を立てた",
    image: "images/annoyed.png",
    p2sentence: "He looked ________ because someone had eaten his lunch.",
    p2sentenceJa: "誰かが彼のお弁当を食べてしまったので、彼は不機嫌そうな顔をしていた。",
    p3hint: "She was really a________ at me.",
    p3hintJa: "彼女は私に本当に腹を立てていた。",
    p3blank: "I touched my sister's things without asking, and she got upset.",
    p3blankJa: "断らずに妹のものを触ったら、彼女は怒ってしまった。",
    p4definition: "unhappy; a little angry",
    p4definitionJa: "不機嫌な；少し腹を立てた",
    usageNote: "「annoyed」は「angry」より弱い怒りを表す。be annoyed at/with + 人、be annoyed about + こと、の形で使われる。",
    related: ["angry（怒っている、より強い感情）", "irritated（イライラした、annoyedとほぼ同義）", "frustrated（思うようにいかずもどかしい）"]
  },
  {
    word: "connected",
    pos: "adj.",
    definition: "feeling close (to someone)",
    definitionJa: "（誰かと）つながっていると感じる",
    image: "images/connected.png",
    p2sentence: "After talking every day, they felt very ________ to each other.",
    p2sentenceJa: "毎日話すうちに、ふたりはお互いにとても繋がっていると感じるようになった。",
    p3hint: "Talking so often makes us feel c________ to each other.",
    p3hintJa: "こんなに頻繁に話すと、お互いに繋がっていると感じるようになる。",
    p3blank: "We chat online every day even though we live far apart.",
    p3blankJa: "遠く離れて住んでいるのに、毎日オンラインでチャットしている。",
    p4definition: "feeling close (to someone)",
    p4definitionJa: "（誰かと）つながっていると感じる",
    usageNote: "感情的な結びつきを表す場合は feel connected to ~ の形が多い。デジタル機器が「接続されている」という意味でも使う多義語。",
    related: ["close（親しい、距離的・心理的に近い）", "bonded（絆で結ばれた）", "disconnected（切断された・疎遠な、反対語）"]
  },
  {
    word: "convenient",
    pos: "adj.",
    definition: "easy to use or get",
    definitionJa: "使いやすい；手に入りやすい",
    image: "images/convenient.png",
    p2sentence: "The app is very ________ because you can use it anywhere.",
    p2sentenceJa: "そのアプリはどこでも使えるので、とても便利だ。",
    p3hint: "It is very c________ for everyone to use.",
    p3hintJa: "それは誰にとってもとても便利だ。",
    p3blank: "The new app works on any phone and is easy to download.",
    p3blankJa: "その新しいアプリはどのスマートフォンでも動き、簡単にダウンロードできる。",
    p4definition: "easy to use or get",
    p4definitionJa: "使いやすい；手に入りやすい",
    usageNote: "名詞形は convenience（便利さ）。convenience store（コンビニ）のように複合語でも頻出する。",
    related: ["convenience（便利さ、名詞形）", "handy（手軽な、口語的）", "accessible（利用しやすい・入手しやすい）"]
  },
  {
    word: "crazy about",
    pos: "adj. phr.",
    definition: "liking someone or something a lot",
    definitionJa: "〜に夢中である；〜が大好きだ",
    image: "images/crazy-about.png",
    p2sentence: "She is ________ this singer and knows all his songs.",
    p2sentenceJa: "彼女はこの歌手に夢中で、彼の曲を全部知っている。",
    p3hint: "He is c________ a________ basketball.",
    p3hintJa: "彼はバスケットボールに夢中だ。",
    p3blank: "My brother never misses a basketball game and has all the team's goods.",
    p3blankJa: "弟はバスケの試合を一度も欠かさず見て、チームのグッズを全部持っている。",
    p4definition: "liking someone or something a lot",
    p4definitionJa: "〜に夢中である；〜が大好きだ",
    usageNote: "be crazy about + 名詞 の形で使う熟語表現。対象は人にも物にも使える（例：crazy about her／crazy about soccer）。",
    related: ["be into ~（〜にはまっている、口語的）", "be obsessed with ~（〜に執着している、より強い）", "be fond of ~（〜が好きだ、控えめな言い方）"]
  },
  {
    word: "digital",
    pos: "adj.",
    definition: "using computer technology",
    definitionJa: "コンピューター技術を使った；デジタルの",
    image: "images/digital.png",
    p2sentence: "We live in a ________ age where everything is on a screen.",
    p2sentenceJa: "私たちは何もかもが画面上にあるデジタル時代に生きている。",
    p3hint: "Our school life has become very d________.",
    p3hintJa: "私たちの学校生活はとてもデジタル化された。",
    p3blank: "We use tablets and apps for almost everything in school now.",
    p3blankJa: "今や学校での授業のほぼすべてにタブレットやアプリを使っている。",
    p4definition: "using computer technology",
    p4definitionJa: "コンピューター技術を使った；デジタルの",
    usageNote: "反対語は analog（アナログの）。digital camera、digital age など名詞を修飾する形でよく使われる。",
    related: ["analog（アナログの、反対語）", "online（オンラインの）", "technological（技術的な）"]
  },
  {
    word: "disagree",
    pos: "v.",
    definition: "to have a different opinion",
    definitionJa: "意見が異なる；同意しない",
    image: "images/disagree.png",
    p2sentence: "The two friends often ________ about which sport is the best.",
    p2sentenceJa: "ふたりの友達はどのスポーツが一番かについてよく意見が分かれる。",
    p3hint: "We always d________ about which season is better.",
    p3hintJa: "私たちはいつもどの季節がよいかについて意見が合わない。",
    p3blank: "My friend thinks summer is the best season, but I think winter is.",
    p3blankJa: "友達は夏が一番だと思っているが、私は冬だと思っている。",
    p4definition: "to have a different opinion",
    p4definitionJa: "意見が異なる；同意しない",
    usageNote: "disagree with + 人/意見、disagree about + 話題 の形をとる。反対語は agree（同意する）。",
    related: ["agree（同意する、反対語）", "argue（議論する・口論する）", "disagreement（意見の不一致、名詞形）"]
  },
  {
    word: "global",
    pos: "adj.",
    definition: "relating to the whole world",
    definitionJa: "世界全体に関わる；グローバルな",
    image: "images/global.png",
    p2sentence: "Climate change is a ________ problem we all need to solve.",
    p2sentenceJa: "気候変動は私たち全員が解決しなければならない世界的な問題だ。",
    p3hint: "It is a g________ problem that we all share.",
    p3hintJa: "それは私たち全員が共有する世界的な問題だ。",
    p3blank: "Air pollution does not stop at any country's border.",
    p3blankJa: "大気汚染はどの国の国境でも止まらない。",
    p4definition: "relating to the whole world",
    p4definitionJa: "世界全体に関わる；グローバルな",
    usageNote: "Academic Wordとして頻出。global warming（地球温暖化）、global economy（世界経済）のように使われる。",
    related: ["worldwide（世界中で、副詞・形容詞）", "international（国際的な）", "local（地元の、対義語的に使われる）"]
  },
  {
    word: "instrument",
    pos: "n.",
    definition: "a thing you use to make music, such as a guitar",
    definitionJa: "楽器（ギターなど音楽を奏でるもの）",
    image: "images/instrument.png",
    p2sentence: "She played a beautiful ________ at the school concert.",
    p2sentenceJa: "彼女は学校のコンサートで美しい楽器を演奏した。",
    p3hint: "The violin is her favorite i________.",
    p3hintJa: "バイオリンは彼女のお気に入りの楽器だ。",
    p3blank: "She has been playing the violin since she was five years old.",
    p3blankJa: "彼女は5歳からバイオリンを弾いている。",
    p4definition: "a thing you use to make music, such as a guitar",
    p4definitionJa: "楽器（ギターなど音楽を奏でるもの）",
    usageNote: "musical instrument という形でも使われる。医療や科学で使う「器具」の意味も持つ多義語。",
    related: ["musical instrument（楽器、正式な言い方）", "play an instrument（楽器を演奏する）", "tool（道具、より一般的な語）"]
  },
  {
    word: "last",
    pos: "adj.",
    definition: "nearest in the past to the present time",
    definitionJa: "最近の；直前の（過去の中で現在に一番近い）",
    image: "images/last.png",
    p2sentence: "Do you remember the ________ time we met?",
    p2sentenceJa: "私たちが最後に会ったときのことを覚えていますか？",
    p3hint: "When was the l________ time you called your grandparents?",
    p3hintJa: "祖父母に電話したのは最後にいつでしたか？",
    p3blank: "I cannot remember exactly when we first met at school.",
    p3blankJa: "学校で初めて会ったのが正確にいつだったか思い出せない。",
    p4definition: "nearest in the past to the present time",
    p4definitionJa: "最近の；直前の（過去の中で現在に一番近い）",
    usageNote: "last week／last year のように時を表す語の前に置く用法と、the last time（最後の時）という用法の両方を覚える。",
    related: ["recent（最近の）", "previous（前の、ひとつ前を指す）", "final（最終的な、順序の最後を指す）"]
  },
  {
    word: "loud",
    pos: "adj.",
    definition: "making a lot of sound or noise; not quiet",
    definitionJa: "大きな音を出す；うるさい；静かでない",
    image: "images/loud.png",
    p2sentence: "The music from next door was so ________ that I couldn't sleep.",
    p2sentenceJa: "隣から聞こえる音楽があまりにも大きくて、眠れなかった。",
    p3hint: "The music was so l________ that I could not rest.",
    p3hintJa: "音楽があまりに大きくて、休むことができなかった。",
    p3blank: "The neighbors were having a party and the music was too strong to sleep through.",
    p3blankJa: "隣人たちがパーティーをしていて、音楽が大きすぎて眠れなかった。",
    p4definition: "making a lot of sound or noise; not quiet",
    p4definitionJa: "大きな音を出す；うるさい；静かでない",
    usageNote: "音量だけでなく、loud colors（派手な色）のように「目立つ・派手な」という意味でも使われる。",
    related: ["noisy（騒がしい、loudと近い意味）", "quiet（静かな、反対語）", "volume（音量、名詞）"]
  },
  {
    word: "memory",
    pos: "n.",
    definition: "something you remember from the past",
    definitionJa: "過去の記憶；思い出",
    image: "images/memory.png",
    p2sentence: "Looking at old photos brings back happy ________.",
    p2sentenceJa: "古い写真を見ると、幸せな思い出がよみがえる。",
    p3hint: "Those photos are full of happy m________.",
    p3hintJa: "あれらの写真は幸せな思い出でいっぱいだ。",
    p3blank: "Looking at old photos brings back feelings from long ago.",
    p3blankJa: "古い写真を見ると、昔の気持ちがよみがえってくる。",
    p4definition: "something you remember from the past",
    p4definitionJa: "過去の記憶；思い出",
    usageNote: "可算名詞として「a memory（思い出のひとつ）」、不可算名詞として「memory（記憶力）」の両方の使い方がある。",
    related: ["remember（覚えている、動詞形）", "memorize（記憶する・暗記する）", "nostalgia（懐かしさ）"]
  },
  {
    word: "old-fashioned",
    pos: "adj.",
    definition: "not modern in style",
    definitionJa: "流行遅れの；古風な",
    image: "images/old-fashioned.png",
    p2sentence: "My grandmother's sewing machine looks very ________.",
    p2sentenceJa: "祖母のミシンはとても古風に見える。",
    p3hint: "People say it looks very o________-f________.",
    p3hintJa: "それはとても古風に見えると人々は言う。",
    p3blank: "That style of dress was popular in the 1950s and looks nothing like today's fashion.",
    p3blankJa: "そのドレスのスタイルは1950年代に流行したもので、現代のファッションとは全く異なる。",
    p4definition: "not modern in style",
    p4definitionJa: "流行遅れの；古風な",
    usageNote: "ハイフンでつながる複合形容詞。否定的な意味だけでなく、「趣のある・伝統的な」という肯定的な文脈でも使われる。",
    related: ["modern（現代的な、反対語）", "vintage（年代物の、肯定的な響き）", "outdated（時代遅れの、より否定的）"]
  },
  {
    word: "percent",
    pos: "n.",
    definition: "one part in a hundred; %",
    definitionJa: "パーセント；100分の1",
    image: "images/percent.png",
    p2sentence: "About 30 ________ of students walk to school.",
    p2sentenceJa: "生徒の約30パーセントが徒歩で通学している。",
    p3hint: "That means only ten p________ of the class passed.",
    p3hintJa: "それはクラスのたった10パーセントしか合格しなかったことを意味する。",
    p3blank: "Only two students out of twenty got a perfect score.",
    p3blankJa: "20人中たった2人だけが満点を取った。",
    p4definition: "one part in a hundred; %",
    p4definitionJa: "パーセント；100分の1",
    usageNote: "数字＋percent of＋名詞 の形で使う。文中では % の記号で書かれることも多い。",
    related: ["percentage（割合、より一般的な名詞）", "ratio（比率）", "fraction（分数・一部）"]
  },
  {
    word: "remind",
    pos: "v.",
    definition: "to make someone remember",
    definitionJa: "（人に）思い出させる",
    image: "images/remind.png",
    p2sentence: "The smell of cookies always ________ me of my childhood.",
    p2sentenceJa: "クッキーの香りはいつも私に子供の頃を思い出させる。",
    p3hint: "It r________ me of the time I spent at her house.",
    p3hintJa: "それは私に彼女の家で過ごした時間を思い出させる。",
    p3blank: "The scent of my grandmother's cooking always brings her face to mind.",
    p3blankJa: "祖母の料理の香りはいつも彼女の顔を思い起こさせる。",
    p4definition: "to make someone remember",
    p4definitionJa: "（人に）思い出させる",
    usageNote: "remind 人 of 物事 の形が頻出（例：remind me of you）。remember（自分が覚えている）と混同しないよう注意。",
    related: ["remember（覚えている、自動詞的）", "reminder（思い出させるもの・備忘録）", "recall（思い出す）"]
  },
  {
    word: "spend",
    pos: "v.",
    definition: "to use time doing an activity",
    definitionJa: "（時間を）〜して過ごす",
    image: "images/spend.png",
    p2sentence: "On weekends, I like to ________ time playing video games.",
    p2sentenceJa: "週末は、ビデオゲームをして時間を過ごすのが好きだ。",
    p3hint: "I s________ the whole day gaming.",
    p3hintJa: "私は一日中ゲームをして過ごした。",
    p3blank: "I played video games all Saturday without stopping.",
    p3blankJa: "土曜日は止まらずに一日中ビデオゲームをした。",
    p4definition: "to use time doing an activity",
    p4definitionJa: "（時間を）〜して過ごす",
    usageNote: "spend + 時間 + -ing の形で使う（例：spend time reading）。お金を使う場合も同じ動詞 spend を使う。",
    related: ["spend money（お金を使う、同じ動詞の別用法）", "pass the time（時間をやり過ごす）", "waste（無駄に使う、否定的）"]
  },
  {
    word: "stadium",
    pos: "n.",
    definition: "a very big building, often without a roof, for concerts or sports",
    definitionJa: "スタジアム（コンサートやスポーツのための大きな建物）",
    image: "images/stadium.png",
    p2sentence: "The concert was held in a huge ________ downtown.",
    p2sentenceJa: "コンサートは街の中心にある大きなスタジアムで開催された。",
    p3hint: "It took place in a famous s________ in the city.",
    p3hintJa: "それは市内の有名なスタジアムで行われた。",
    p3blank: "The concert was held in a huge outdoor venue that fits thousands of people.",
    p3blankJa: "コンサートは何千人もの人を収容できる大きな屋外会場で開催された。",
    p4definition: "a very big building, often without a roof, for concerts or sports",
    p4definitionJa: "スタジアム（コンサートやスポーツのための大きな建物）",
    usageNote: "Academic Wordとして頻出。屋根がない大規模施設を指すことが多く、屋内施設には arena が使われる傾向がある。",
    related: ["arena（屋内競技場）", "venue（会場、より一般的な語）", "field（競技場・フィールド）"]
  },
  {
    word: "streaming",
    pos: "adj.",
    definition: "playing on a phone or computer while coming from the Internet",
    definitionJa: "インターネットから受信しながら再生する；ストリーミングの",
    image: "images/streaming.png",
    p2sentence: "I was ________ the game on my phone during lunch.",
    p2sentenceJa: "昼食中、スマートフォンでゲームをストリーミング再生していた。",
    p3hint: "She was s________ the video on her way home.",
    p3hintJa: "彼女は帰宅途中に動画をストリーミング再生していた。",
    p3blank: "She was watching a show on her phone while downloading it at the same time.",
    p3blankJa: "彼女はスマートフォンで番組を見ながら、同時にダウンロードしていた。",
    p4definition: "playing on a phone or computer while coming from the Internet",
    p4definitionJa: "インターネットから受信しながら再生する；ストリーミングの",
    usageNote: "動詞 stream の現在分詞形でもあり、形容詞としても動詞としても使える（例：I'm streaming a movie）。",
    related: ["download（ダウンロードする、対になる概念）", "broadcast（放送する）", "online（オンラインの）"]
  },
  {
    word: "surprising",
    pos: "adj.",
    definition: "not expected; unusual",
    definitionJa: "予期しない；驚くべき",
    image: "images/surprising.png",
    p2sentence: "It was ________ to see snow in April.",
    p2sentenceJa: "4月に雪が見られるとは驚きだった。",
    p3hint: "It was really s________ to see snow at that time of year.",
    p3hintJa: "その時期に雪が見られるとは本当に驚きだった。",
    p3blank: "Nobody expected it to snow in the middle of April.",
    p3blankJa: "4月の中頃に雪が降るとは誰も予想していなかった。",
    p4definition: "not expected; unusual",
    p4definitionJa: "予期しない；驚くべき",
    usageNote: "surprising（物事が人を驚かせる）と surprised（人が驚いている）の使い分けに注意。It is surprising that... の構文も頻出。",
    related: ["surprised（驚いている、感情を表す形容詞）", "unexpected（予期しない）", "shocking（衝撃的な、より強い驚き）"]
  },
  {
    word: "well-known",
    pos: "adj.",
    definition: "famous; known by many people",
    definitionJa: "有名な；多くの人に知られている",
    image: "images/well-known.png",
    p2sentence: "This song is ________ all over the world.",
    p2sentenceJa: "この曲は世界中で有名だ。",
    p3hint: "She is w________-k________ around the globe.",
    p3hintJa: "彼女は世界中で有名だ。",
    p3blank: "This singer's name is recognized in almost every country in the world.",
    p3blankJa: "この歌手の名前はほぼすべての国で知られている。",
    p4definition: "famous; known by many people",
    p4definitionJa: "有名な；多くの人に知られている",
    usageNote: "ハイフンでつながる複合形容詞。well known（ハイフンなし）は be動詞の後で使う形で、名詞の前ではハイフンを入れる。",
    related: ["famous（有名な、より一般的）", "popular（人気のある）", "renowned（名高い、より文語的）"]
  }
];
